version: 0.2

env:
  shell: bash
  privileged-mode: true
  secrets-manager:
    WPSCAN_API_TOKEN: "prod/wordpress/infra:WPSCAN_API_TOKEN"

phases:
  install:
    commands:
      - echo "--- INSTALLATION DES OUTILS ---"
      - sudo apt-get update
      # Gitleaks
      - wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz && tar -zxvf gitleaks_8.18.2_linux_x64.tar.gz && mv gitleaks /usr/local/bin/
      # Trivy
      - export TRIVY_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
      - wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - tar zxvf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - sudo mv trivy /usr/local/bin/
      # Checkov
      - pip3 install checkov
      # Terraform
      - sudo rm -rf /usr/local/bin/terraform* || true
      - sudo rm -f /usr/bin/terraform* || true
      - |
        wget -q https://releases.hashicorp.com/terraform/1.14.8/terraform_1.14.8_linux_amd64.zip
        
        unzip -o -q terraform_1.14.8_linux_amd64.zip
        
        sudo mv terraform /usr/local/bin/terraform
        sudo chmod +x /usr/local/bin/terraform
        rm terraform_1.14.8_linux_amd64.zip LICENSE.txt
  

      - sudo apt-get update -qq
      - sudo apt-get install -y -qq unzip wget jq curl awscli

  pre_build:
    commands:
      # Scan GitLeaks
      - echo "--- ETAPE 1 GITLEAKS (Secrets) ---"
      - gitleaks detect --source . --exit-code 1

      # Scan Checkov
      - echo "--- ETAPE 2 CHECOKV (Infra as Code) ---"
      - checkov -d terraform/ --framework terraform --soft-fail

  build:
    commands:
      # Build image docker sur l'environnement propre
      - docker --version
      - docker build -t wordpress_secu DockerFile/wp/
      - docker build -t mariadb_secu DockerFile/db/


      # Scan Trivy
      - echo "--- ETAPE 3 TRIVY (Scan Image Docker - Bloquant) ---"
      - |
        IMAGES="wordpress_secu:latest mariadb_secu:latest"

        for img in $IMAGES; do
          trivy image --severity CRITICAL,HIGH \
                --exit-code 1 \
                --format table \
                --ignore-unfixed \
                --ignorefile .trivyignore \
                "$img"
          done

      # Deploiement Terraform
      - cd terraform
      - terraform init
      - terraform validate
      - terraform fmt -check
      - terraform plan -out=tfplan -var-file="dev.tfvars"
      - aws s3 cp tfplan s3://your-bucket/tfplans/dev-$(date +%Y%m%d-%H%M).plan

      # Timer
      - echo "--- ETAPE 6 ATTENTE DU SITE ---"
      - |
        timeout=300; counter=0
        until $(curl --output /dev/null --silent --head --fail $INSTANCE_URL); do
          if [ $counter -eq $timeout ]; then exit 1; fi
          sleep 5 && counter=$((counter+5))
        done

      # Owasp ZAP
      - echo "--- ETAPE 7 OWASP ZAP (Scan Dynamique) ---"
      - |
        docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t $INSTANCE_URL -r security-reports/zap_report.html || [ $? -ne 4 ]

      # WPScan
      - echo "--- ETAPE 8 WPSCAN (Scan Spécifique WordPress) ---"
      - |
        docker run --rm wpscanteam/wpscan \
          --url $INSTANCE_URL --api-token $WPSCAN_API_TOKEN \
          --enumerate p,t,u --fail-on-vulnerability --output security-reports/wpscan_report.txt

  post_build:
    commands:
      - echo "Pipeline terminée avec succès"

artifacts:
  files:
    - 'security-reports/*'
